In [9]:
import pandas as pd
import os
import config
from sqlalchemy import create_engine
import isodate

In [10]:
# Create the database URL
DATABASE_URL = f'{config.DATABASE_TYPE}+{config.DBAPI}://{config.USER}:{config.PASSWORD}@{config.ENDPOINT}:{config.PORT}/{config.YOUTUBE_DATABASE}'

# Create the engine
engine = create_engine(DATABASE_URL)

In [11]:
query = '''
SELECT * 
FROM "VIDEO_STATISTICS"

'''

# Read the table into a DataFrame
vaushYT_df = pd.read_sql(query, engine)
vaushYT_df.head()

,VIDEO_ID,TITLE,DESCRIPTION,PUBLISHED_AT,VIEW_COUNT,LIKE_COUNT,DISLIKE_COUNT,COMMENT_COUNT,DURATION
0,22DAbcgPxwU,TYT Is Right,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-06 18:10:20,44920,2680,0,709,PT20M47S
1,g5EK9VpkQZo,Labour Enjoys EMBARRASSING Non-Victory As DOOM...,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-05 18:10:59,55635,3187,0,1052,PT2M41S
2,ozdB1zlUUvk,"Oh, I Didn’t Realize Jimmy Dore Was THIS Far Gone",🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-05 14:00:46,71782,3135,0,702,PT14M44S
3,OC1dHP9yZrw,The DISTURBING New Revelations About Trump,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-04 21:37:02,109298,6869,0,1205,PT8M6S
4,THNvpGrn4JE,Biden's Team FAILS In DISASTROUS Briefing,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-03 21:42:23,86853,2943,0,1103,PT1H29M49S

In [12]:
vaushYT_df

,VIDEO_ID,TITLE,DESCRIPTION,PUBLISHED_AT,VIEW_COUNT,LIKE_COUNT,DISLIKE_COUNT,COMMENT_COUNT,DURATION
0,22DAbcgPxwU,TYT Is Right,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-06 18:10:20,44920,2680,0,709,PT20M47S
1,g5EK9VpkQZo,Labour Enjoys EMBARRASSING Non-Victory As DOOM...,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-05 18:10:59,55635,3187,0,1052,PT2M41S
2,ozdB1zlUUvk,"Oh, I Didn’t Realize Jimmy Dore Was THIS Far Gone",🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-05 14:00:46,71782,3135,0,702,PT14M44S
3,OC1dHP9yZrw,The DISTURBING New Revelations About Trump,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-04 21:37:02,109298,6869,0,1205,PT8M6S
4,THNvpGrn4JE,Biden's Team FAILS In DISASTROUS Briefing,🔴 Website - https://www.vaush.gg/\n💵 Patreon ...,2024-07-03 21:42:23,86853,2943,0,1103,PT1H29M49S
...,...,...,...,...,...,...,...,...,...
2204,4CZUNd-N1ko,How to TRIGGER Reactionaries with FACTS and LOGIC,Please be critical of me down in the comments ...,2019-02-03 03:39:16,190899,10260,0,1390,PT14M24S
2205,3G9x8rgrGWQ,1/25/19 Stream Debate with the LEGENDARY Paste...,Hopefully the first of many debates to come.\n...,2019-01-27 06:40:21,17279,460,0,122,PT2H2M29S
2206,c8yQDtLeb14,My Longest Yeah Boi Yet + Thoughts on Israel,This is the one I'll be remembered for. UpGera...,2019-01-23 23:37:19,28895,1418,0,75,PT1M13S
2207,JlJkVPn2NRM,A Dialogue on Violent Revolution,Watch me struggle to find a format which works...,2019-01-22 23:05:01,26586,1374,0,169,PT14M55S
2208,-94STO1-D5Q,E N L I G H T E N E D C E N T R I S M,Thought I'd take a shot at YouTube stuff. I'm ...,2019-01-14 06:35:49,140388,6761,0,910,PT19M39S

In [13]:
# Function to convert ISO 8601 duration to minutes
def convert_to_minutes(duration):
    parsed_duration = isodate.parse_duration(duration)
    total_minutes = parsed_duration.total_seconds() / 60
    return total_minutes

# Apply the function to the Duration column
vaushYT_df['DURATION_MINUTES'] = vaushYT_df['DURATION'].apply(convert_to_minutes)